name: Testing Actions Environment

on:
  workflow_dispatch:

  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    name: Initial configuration and testing

    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: ./dist

      # Runs a single command using the runners shell
      - name: Configure NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    name: Build

    needs: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm run build
          ls -l
      
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    name: Deploy application

    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Start application
        run: |
          mv dist/artifact/* dist
          rm -rf dist/artifact
          npm run start
